-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.NAME
# SELECT *
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I
ON O.NAME = I.NAME and O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.NAME is null and O.NAME is not null
ORDER BY O.ANIMAL_ID