# -- 코드를 입력하세요
# SELECT I.FLAVOR as FLAVOR
# FROM ICECREAM_INFO I
# JOIN FIRST_HALF F
# ON I.FLAVOR = F.FLAVOR
# WHERE TOTAL_ORDER >= 3000
# AND I.FLAVOR = "fruit_based"
# ORDER BY TOTAL_ORDER DESC

SELECT I.FLAVOR
FROM ICECREAM_INFO I
JOIN FIRST_HALF F
  ON I.FLAVOR = F.FLAVOR
WHERE F.TOTAL_ORDER >= 3000
  AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY F.TOTAL_ORDER DESC;