-- 코드를 입력하세요
SELECT B.BOOK_ID as BOOK_ID, A.AUTHOR_NAME as AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, "%Y-%m-%d") as PUBLISHED_DATE
FROM BOOK as B, AUTHOR as A
WHERE A.AUTHOR_ID = B.AUTHOR_ID and B.CATEGORY = "경제"
ORDER BY B.PUBLISHED_DATE
